# Generated by Django 3.1 on 2022-05-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='keywords',
            field=models.CharField(default='Ключевые слова', max_length=120),
        ),
    ]
